### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by nirala69** [nirala69/open_source_start#74]

**Comment by mayorJAY** [comment]
@nirala69 Can I take up this issue?

**Comment by nirala69** [comment]
Sure @mayorJAY go for it

**Comment by mayorJAY** [comment]
@nirala69 we can adopt an existing and recognized code of conduct right?

**Comment by mayorJAY** [comment]
@nirala69 Pls your email address is needed as the maintainer of the project

**Comment by nirala69** [comment]
@mayorJAY 

arunoday.d19@gmail.com
